name: Build & deploy

on:
  push:
    branches:
      - main
      - dev

jobs:
  buildDeploy:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: |
          **/.next
          **/public/c
          **/node_modules
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-

    - name: Install Node.js 21
      uses: actions/setup-node@v4
      with:
        node-version: 21.x

    - name: Install NPM packages
      run: npm install

    - name: Build project
      env:
        NEXT_PUBLIC_PASSWORD: ${{ secrets.NEXT_PUBLIC_PASSWORD }}
      run: |
        echo "NEXT_PUBLIC_PASSWORD=$NEXT_PUBLIC_PASSWORD" >> .env.local
        npm run build

    - name: Deploy
      if: github.ref == 'refs/heads/main'
      uses: FirebaseExtended/action-hosting-deploy@v0.10.0
      with:
        repoToken: '${{ secrets.ACCESS_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_CERT }}'
        channelId: live
        projectId: gdsc23-cert
        target: gdsc-certificates

    - name: Deploy preview
      if: github.ref != 'refs/heads/main'
      uses: FirebaseExtended/action-hosting-deploy@v0.10.0
      with:
        repoToken: '${{ secrets.ACCESS_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GDSC_CERT }}'
        channelId: preview
        projectId: gdsc23-cert
        target: gdsc-certificates
